vim -s ../piwik.vim den-beboelige-zone.html
vim -s ../piwik.vim himlens_farve.html
vim -s ../piwik.vim hvad-er-en-partikel.html
vim -s ../piwik.vim hvordan-faar-man-ilt-i-en-rumraket.html
vim -s ../piwik.vim kaffe.html
vim -s ../piwik.vim kan-man-vaere-sikker-paa-hvad-rodforskydning-skyldes.html
vim -s ../piwik.vim liv-i-rummet.html
vim -s ../piwik.vim lyden-af-et-flojt.html
vim -s ../piwik.vim nordlys.html
vim -s ../piwik.vim op_og_ned.html
vim -s ../piwik.vim rumskrot.html
vim -s ../piwik.vim skorpionen.html
vim -s ../piwik.vim spoergetime.html
vim -s ../piwik.vim stjerners_fordeling.html
vim -s ../piwik.vim taarer_af_guld.html
vim -s ../piwik.vim template_svar.html
vim -s ../piwik.vim traet_lys.html
vim -s ../piwik.vim universets-udvidelse.html
vim -s ../piwik.vim universets_geometri_og_uendelighed.html
vim -s ../piwik.vim vaegt-og-masse.html
