vim -s ../piwik.vim atom.html
vim -s ../piwik.vim atom_dk.html
vim -s ../piwik.vim big_bang.html
vim -s ../piwik.vim black_hole.html
vim -s ../piwik.vim cheatsheet.html
vim -s ../piwik.vim cosmic_microwave_background.html
vim -s ../piwik.vim cosmological_simulation.html
vim -s ../piwik.vim cosmology.html
vim -s ../piwik.vim dark_matter.html
vim -s ../piwik.vim galakse.html
vim -s ../piwik.vim galaksedannelse.html
vim -s ../piwik.vim galaxy.html
vim -s ../piwik.vim galaxy_formation.html
vim -s ../piwik.vim gamma_ray_burst.html
vim -s ../piwik.vim gammaglimt.html
vim -s ../piwik.vim geometry_of_the_universe.html
vim -s ../piwik.vim gravitational_waves.html
vim -s ../piwik.vim hvid_dvaerg.html
vim -s ../piwik.vim james-webb-rumteleskop.html
vim -s ../piwik.vim kosmisk_mikrobolgebaggrundsstraaling.html
vim -s ../piwik.vim kosmologi.html
vim -s ../piwik.vim kosmologisk_simulering.html
vim -s ../piwik.vim kvasar.html
vim -s ../piwik.vim large_hadron_collider.html
vim -s ../piwik.vim large_hadron_collider_dk.html
vim -s ../piwik.vim let_stjerne_OLD.html
vim -s ../piwik.vim lyman_alpha.html
vim -s ../piwik.vim lyman_alpha_dk.html
vim -s ../piwik.vim lyman_alpha_forest.html
vim -s ../piwik.vim lyman_alpha_skoven.html
vim -s ../piwik.vim morkt_stof.html
vim -s ../piwik.vim neutron_star.html
vim -s ../piwik.vim neutronstjerne.html
vim -s ../piwik.vim nova.html
vim -s ../piwik.vim nova_dk.html
vim -s ../piwik.vim planetarisk_taage.html
vim -s ../piwik.vim planetary_nebula.html
vim -s ../piwik.vim quasar.html
vim -s ../piwik.vim radiative_transfer.html
vim -s ../piwik.vim red_giant.html
vim -s ../piwik.vim redshift.html
vim -s ../piwik.vim reionisation.html
vim -s ../piwik.vim reionization.html
vim -s ../piwik.vim relativitetsteori.html
vim -s ../piwik.vim relativity_theory.html
vim -s ../piwik.vim rod_kaempe.html
vim -s ../piwik.vim rodforskydning.html
vim -s ../piwik.vim sort_hul.html
vim -s ../piwik.vim spectrum.html
vim -s ../piwik.vim spektrum.html
vim -s ../piwik.vim star.html
vim -s ../piwik.vim star_cluster.html
vim -s ../piwik.vim stardust.html
vim -s ../piwik.vim stjerne.html
vim -s ../piwik.vim stjernehob.html
vim -s ../piwik.vim stjernestov.html
vim -s ../piwik.vim straalingstransport.html
vim -s ../piwik.vim supernova.html
vim -s ../piwik.vim supernova_dk.html
vim -s ../piwik.vim template_ca.html
vim -s ../piwik.vim template_dk.html
vim -s ../piwik.vim the_big_bang.html
vim -s ../piwik.vim ttt.html
vim -s ../piwik.vim tyngdebolger.html
vim -s ../piwik.vim universets_geometri.html
vim -s ../piwik.vim white_dwarf.html
