var anagramList = [
    "A Nepali torso",
    "A lotion rapes",
    "A positron ale",
    "A tale o' prison",
    "Aeropolistan",
    "Aerosol paint",
    "Ain't Oreos, pal!",
    "Airplane soot",
    "Alas, no pie rot",
    "An Oslo pirate",
    "An oat spoiler",
    "Anal isotrope",
    "Anita, <u><a href='https://en.wiktionary.org/wiki/spooler'>spooler</a></u>",
    "Anti-solar Poe",
    "Arion, apostle",
    "Arise, platoon!",
    "Atop Rosaline",
    "Epsilon Aorta",
    "Espa&ntilde;ol ratio",
    "I, Satan looper",
    "Ion astro plea",
    "I, rosa polenta...",
    "Iron at El Paso",
    "Isolator pane",
    "It's near a pool",
    "L.A. senior trap",
    "Le astro piano",
    "Leo, Noa's tapir",
    "Loose part, Ian",
    "No Atari slope",
    "No air postale",
    "O, alien pastor!",
    "Ontario's leap",
    "Opiate Larson",
    "Oriental soap",
    "Orl&eacute;ans' patio",
    "Pale orations",
    "Paolo Stearin",
    "Parasite loon",
    "Personal at I/O",
    "Pi&ntilde;ata looser",
    "Poor Saint Ale",
    "Portoise, Alan!",
    "Rapist on alo&euml;",
    "Re: Pita saloon",
    "Real as potion",
    "Riot espa&ntilde;ola",
    "Rosa antipole",
    "Satin or paleo?",
    "Se&ntilde;orita Op&aacute;l",
    "Snort a <u><a href='https://en.wikipedia.org/wiki/Leipoa'>leipoa</a></u>",
    "Soil near a top",
    "Sort an ape oil",
    "Stolen <u><a href='https://en.wikipedia.org/wiki/Aporia'>aporia</a></u>",
    "Tailor's <u><a href='https://en.wikipedia.org/wiki/Paeon_(prosody)'>paeon</a></u>",
    "Tao-pain? Loser...",
    "Teaspoon rail",
    "<u><a href='https://en.wikipedia.org/wiki/Transient_ischemic_attack'>TIA</a></u>s on parole",
    "To <u><a href='https://en.wikipedia.org/wiki/Palaeornis_cliftii'>Palaeornis</a></u>!",
    "Toenail's porn",
    "<u><a href='https://en.wiktionary.org/wiki/tonsorial'>Tonsorial</a></u> ape"
]

function newAnagram() {
    var randomNumber = Math.floor(Math.random() * (anagramList.length));
    document.getElementById('anagramDisplay').innerHTML = anagramList[randomNumber];
}
