var anagramList = [
    "A Nepali torso",
    "A lotion rapes",
    "A positron ale",
    "A tale o' prison",
    "Aeropolistan",
    "Aerosol paint",
    "Ain't Oreos, pal!",
    "Airplane soot",
    "Alas, no pie rot",
    "An Oslo pirate",
    "An oat spoiler",
    "Anal isotrope",
    "Anita, <u><a href='https://en.wiktionary.org/wiki/spooler'>spooler</a></u>",
    "Anti-solar Poe",
    "Arion, apostle",
    "Arise, platoon!",
    "Atop Rosaline",
    "Epsilon Aorta",
    "I, Satan looper",
    "<u><a href='https://en.wikipedia.org/wiki/Irish_Republican_Army'>I.R.A.</a></u>, so polenta...",
    "Ion astro plea",
    "Iron at El Paso",
    "Isolator pane",
    "It's near a pool",
    "L.A. senior trap",
    "Le astro piano",
    "Leo, Noa's tapir",
    "Parasite loon",
    "No Atari slope",
    "No air postale",
    "O, alien pastor!",
    "Ontario leaps",
    "Opiate Larson",
    "Oriental soap",
    "Orl&eacute;ans' patio",
    "Pale orations",
    "Paolo Stearin",
    "Personal at I/O",
    "Pi&ntilde;ata looser",
    "Poor Saint Ale",
    "Rapist on alo&euml;",
    "Re: Pita saloon",
    "Real as potion",
    "Riot espa&ntilde;ola",
    "Rosa antipole",
    "Satin or paleo?",
    "Se&ntilde;orita Opal",
    "Snort a <u><a href='https://en.wikipedia.org/wiki/Leipoa'>leipoa</a></u>",
    "Soil near a top",
    "Sort an ape oil",
    "Stolen <u><a href='https://en.wikipedia.org/wiki/Aporia'>aporia</a></u>",
    "<u><a href='https://en.wikipedia.org/wiki/Transient_ischemic_attack'>TIA</a></u>s on parole",
    "Tailor's <u><a href='https://en.wikipedia.org/wiki/Paeon_(prosody)'>paeon</a></u>",
    "Tao-pain? Loser...",
    "Teaspoon rail",
    "To <u><a href='https://en.wikipedia.org/wiki/Palaeornis_cliftii'>Palaeornis</a></u>!",
    "Toenail's porn",
    "<u><a href='https://en.wiktionary.org/wiki/tonsorial'>Tonsorial</a></u> ape"
]

function newAnagram() {
    var randomNumber = Math.floor(Math.random() * (anagramList.length));
    document.getElementById('anagramDisplay').innerHTML = anagramList[randomNumber];
}
