vim -s ../piwik.vim albums.html
vim -s ../piwik.vim anagramopela.html
vim -s ../piwik.vim butHansDillerIsAlive.html
vim -s ../piwik.vim comics.html
vim -s ../piwik.vim concerts.html
vim -s ../piwik.vim conferences.html
vim -s ../piwik.vim dillertableDK.html
vim -s ../piwik.vim dillertableEN.html
vim -s ../piwik.vim familie.html
vim -s ../piwik.vim family.html
vim -s ../piwik.vim koncerter.html
vim -s ../piwik.vim konferencer.html
vim -s ../piwik.vim menHansDillerLever.html
vim -s ../piwik.vim mhdl.html
vim -s ../piwik.vim mhdl_noter.html
vim -s ../piwik.vim music.html
vim -s ../piwik.vim musik.html
vim -s ../piwik.vim photos.html
vim -s ../piwik.vim photos_withGutter.html
vim -s ../piwik.vim rabarberkage.html
vim -s ../piwik.vim rdk.html
vim -s ../piwik.vim rec.html
vim -s ../piwik.vim rom.html
vim -s ../piwik.vim rom_before_event-table.html
vim -s ../piwik.vim rum.html
vim -s ../piwik.vim tegneserier.html
vim -s ../piwik.vim tv-serie-quiz.html
vim -s ../piwik.vim ønskeseddel.html
