vim -s particles.vim P2007.html
vim -s particles.vim SN2005at.html
vim -s particles.vim SN2007gr.html
vim -s particles.vim ant.html
vim -s particles.vim butter.html
vim -s particles.vim cloudfall.html
vim -s particles.vim eagle.html
vim -s particles.vim gc.html
vim -s particles.vim key.html
vim -s particles.vim laser.html
vim -s particles.vim moon.html
vim -s particles.vim not.html
vim -s particles.vim pin.html
vim -s particles.vim sombrero.html
vim -s particles.vim supernova.html
vim -s particles.vim template.html
vim -s particles.vim virgo.html
