vim -s ../piwik.vim GC_DK.html
vim -s ../piwik.vim Moon_DK.html
vim -s ../piwik.vim Moon_old.html
vim -s ../piwik.vim Observations.html
vim -s ../piwik.vim Observations_DK.html
vim -s ../piwik.vim P2007.html
vim -s ../piwik.vim P2007_DK.html
vim -s ../piwik.vim P2007_old.html
vim -s ../piwik.vim SN2005at.html
vim -s ../piwik.vim SN2005at_DK.html
vim -s ../piwik.vim SN2005at_old.html
vim -s ../piwik.vim SN2007gr.html
vim -s ../piwik.vim SN2007gr_DK.html
vim -s ../piwik.vim SN2007gr_old.html
vim -s ../piwik.vim ant.html
vim -s ../piwik.vim ant_DK.html
vim -s ../piwik.vim ant_old.html
vim -s ../piwik.vim butter.html
vim -s ../piwik.vim butter_DK.html
vim -s ../piwik.vim butter_old.html
vim -s ../piwik.vim cloudfall.html
vim -s ../piwik.vim eagle.html
vim -s ../piwik.vim eagle_DK.html
vim -s ../piwik.vim eagle_old.html
vim -s ../piwik.vim gc.html
vim -s ../piwik.vim gc_old.html
vim -s ../piwik.vim key.html
vim -s ../piwik.vim key_DK.html
vim -s ../piwik.vim key_old.html
vim -s ../piwik.vim laser.html
vim -s ../piwik.vim laser_DK.html
vim -s ../piwik.vim laser_old.html
vim -s ../piwik.vim m14.html
vim -s ../piwik.vim m14_DK.html
vim -s ../piwik.vim m53.html
vim -s ../piwik.vim m53_DK.html
vim -s ../piwik.vim m9.html
vim -s ../piwik.vim m9_DK.html
vim -s ../piwik.vim moon.html
vim -s ../piwik.vim neowise.html
vim -s ../piwik.vim ngc4833.html
vim -s ../piwik.vim ngc4833_DK.html
vim -s ../piwik.vim not.html
vim -s ../piwik.vim not_1stAttemptFrom_main_pages_layouts_layout-regular-leftsidebar.html.html
vim -s ../piwik.vim pin.html
vim -s ../piwik.vim pin_DK.html
vim -s ../piwik.vim pin_old.html
vim -s ../piwik.vim sombrero.html
vim -s ../piwik.vim sombrero_DK.html
vim -s ../piwik.vim sombrero_old.html
vim -s ../piwik.vim supernova.html
vim -s ../piwik.vim supernova_DK.html
vim -s ../piwik.vim supernova_old.html
vim -s ../piwik.vim template.html
vim -s ../piwik.vim virgo.html
vim -s ../piwik.vim virgo_DK.html
vim -s ../piwik.vim virgo_old.html
